In [2]:
%matplotlib inline
import sympy as sy
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [5]:
# the data used in this notebook is get from here: https://www.kaggle.com/datasets/rounakbanik/the-movies-dataset

ratings = pd.read_csv('ratings_small.csv', dtype={'movieId': 'object', 'userId': 'object'})
movies = pd.read_csv('movies_metadata.csv')
df = ratings.merge(movies, left_on='movieId', right_on='id')[['original_title',  'userId', 'rating']]
df = df.rename(columns={'original_title': 'movie'})

In [6]:
most_active_users = df.userId.value_counts()[:10].index

In [7]:
users_by_movie = df[(df['userId'].isin(most_active_users))].groupby('movie').count()['userId'] 
most_common_movies = users_by_movie[users_by_movie <= 9].sort_values(ascending=False).index[:15]

In [8]:
selected_samples = df[(df['userId'].isin(most_active_users)) & (df['movie'].isin(most_common_movies))]

In [9]:
ratings_df = selected_samples.pivot(values='rating', columns='userId', index='movie')
ratings_df

userId                  15   30  311  452  468  509  547  564  624   73
movie
88 Minutes             2.0  4.0  2.0  NaN  2.0  2.0  1.5  2.0  3.0  3.5
A Time to Kill         3.0  5.0  2.5  2.0  2.0  3.0  NaN  4.0  3.0  3.0
Barry Lyndon           4.0  NaN  3.0  3.0  3.0  3.5  4.0  5.0  4.0  2.5
Gleaming the Cube      2.5  4.0  4.0  NaN  3.0  3.0  3.0  4.0  3.0  4.0
Judgment Night         4.0  4.0  4.0  4.0  3.5  3.0  2.5  1.0  NaN  4.5
License to Wed         5.0  4.0  NaN  2.0  3.0  4.0  3.5  5.0  4.0  5.0
Lonely Hearts          5.0  5.0  3.0  4.0  4.0  4.0  5.0  5.0  NaN  4.0
Mr. Holland's Opus     2.0  1.0  3.5  3.0  2.5  2.0  NaN  4.0  4.0  3.5
Psycho                 2.0  3.0  4.0  4.0  3.0  3.0  3.0  5.0  3.0  NaN
Rain Man               4.0  4.0  3.5  3.0  NaN  2.0  3.0  5.0  3.0  3.0
Sleepless in Seattle   5.0  5.0  NaN  5.0  4.0  5.0  4.0  2.0  5.0  5.0
The 39 Steps           5.0  4.0  4.0  4.0  3.5  5.0  NaN  2.0  5.0  4.5
The Endless Summer     4.5  5.0  4.0  NaN  2.5  4.0  4.0  4.0  2.0  3.5
The Forbidden Kingdom  1.0  5.0  3.0  NaN  3.0  4.5  5.0  3.0  4.0  3.5
The Terminal           2.5  3.0  3.0  NaN  4.0  3.5  5.0  4.0  4.0  3.5

In [10]:
ratings_df.to_csv('small_movie_ratings.csv')